# Generated by Django 4.0 on 2024-02-23 12:40

from django.db import migrations, models
import speaker.models


class Migration(migrations.Migration):
    dependencies = [
        ("speaker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="voice_sample",
            field=models.FileField(upload_to=speaker.models.Individual.speaker_directory_path),
        ),
    ]
